### ISSUE TITLE
Question about upstream port

### ISSUE THREAD

**Issue by AntonioND** [andreiw/raspberry-pi3-atf#1]
Is there anything in this port that the upstream port of the Trusted Firmware to the Raspberry Pi 3 doesn't have?

https://github.com/ARM-software/arm-trusted-firmware/tree/master/plat/rpi3

https://github.com/ARM-software/arm-trusted-firmware/blob/master/docs/plat/rpi3.rst

If so, I'd like to know. Maybe there's something that the upstream port should have that it doesn't right now.

**Comment by andreiw** [comment]
So this specific version is based on https://github.com/ardbiesheuvel/arm-trusted-firmware/tree/rpi3, which was a pre-upstream variant, if I understand correctly.

I've no idea where the upstream ATF is, but the one I based on had a few bugs around PSCI CPU_ON support. Then there is https://github.com/andreiw/raspberry-pi3-atf/commit/1c97dfe03e1636a587d9e1e683f37d1b4fdecc9b (to allow the DTB to be passed through to Tiano), and https://github.com/andreiw/raspberry-pi3-atf/commit/3565e7390b6e67d8e589a8586f9bf527c980d214 (which fixed a WoA issue). Among the silly things is https://github.com/andreiw/raspberry-pi3-atf/commit/b1f5b0343b10562685dbe603585cba565a4bb54a.

If you/someone wants to validate https://github.com/andreiw/RaspberryPiPkg with upstream ATF, that would be fantastic. I really don't have time to upstream anything.
